project_view/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('tpl/', include('tpl.urls')),
    path('uploader/', include('uploader.urls')),
    path('csrf/', include('csrf.urls')),
    path('jsonp/', include('jsonp.urls')),
    path('user/',include('user.urls')),
    path('cookie/',include('cookie.urls')),
    path('pro_response/',include('pro_response.urls')),
    path('ajax/',include('ajax.urls')),
    path('post_app/',include('post_app.urls')),
    path('get_app/',include('get_app.urls')),
    # path('http/',include(m_http.urls)),
    path('employee/', include('employee.urls')),
    # path('blog/', include('blog.urls')),
    # path('', include('articles.urls')),
    path('rs/', include('rs.urls')),
    path('admin/', admin.site.urls),
]

rs/urls.py
# -*- coding:utf-8 -*-
from django.urls import path
from . import views

app_name = 'rs'
urlpatterns = [
    path(route="test_rs/<int:pk>/", view=views.test_rs, name='test_rs'),
    path(route="test01/", view=views.test01, name='test01'),
]

user/urls.py
# -*- coding:utf-8 -*-
from django.urls import path
from . import views
from django.views.generic.base import RedirectView
app_name = 'user'

urlpatterns = [
    path('template/<int:pk>/', views.template, name='template'),
    path('detail/<slug:slug_value>/', views.UserDetailView.as_view(), name='detail'),
    # path('detail/<int:abc>/', views.UserDetailView.as_view(), name='detail'),
    path('list/', views.UserListView.as_view(), name='list'),

    path('redirect/', views.UserRedirectView.as_view(), name='redirect'),

    path('go-to-django/',
         RedirectView.as_view(url='https://www.djangoproject.com'),
         name='go-to-django'),

    path('go-to-home/',
         RedirectView.as_view(url='../home/'),
         name='go-to-home'),

    path('home/', views.HomeView.as_view(), name='home'),
    path('login/',views.login,name='login'),

    path('index/',views.index,name='index'),
    path('logout/',views.logout,name='logout'),
    path('',views.UserView.as_view(),name=''),
]

user/models.py
from django.db import models
from uuslug.uuslug import slugify

"""定义UserInfo表"""


class UserInfo(models.Model):
    userName = models.CharField(max_length=20, unique=True, db_column="user_name")
    password = models.CharField(max_length=50)
    slugUrl = models.SlugField(default='',db_column='slug_url')
    header = models.CharField(max_length=255)
    age = models.IntegerField(default=0, db_column='age')

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        self.slugUrl = slugify(self.userName)  # 生成一个slug值
        super().save(force_insert, force_update, using, update_fields)

"""定义UserContact表跟UserInfo表时一对一"""
class UserContact(models.Model):
    userInfo = models.OneToOneField(UserInfo, on_delete=models.CASCADE)
    phone = models.CharField(max_length=18)
    email = models.EmailField(max_length=50)

user/views.py
from django.shortcuts import render
from django.views.decorators.http import require_POST,require_GET
from .models import UserInfo
from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse
from django.views.generic import View
from django.views.generic.list import ListView
from django.template.response import TemplateResponse
from datetime import timedelta
# Create your views here.
def index(request):
    """登录页面"""
    # 先从session中获取登录用户信息，是否存在
    username = request.session.get('userName')
    if username is not None and username.strip() != '':
        return render(request, 'login_success.html', {'userName':username})
    else:
        return render(request, "login.html")


@require_POST
def login(request):
    """登录"""
    # 先获取参数
    username = request.POST.get('userName')
    password = request.POST.get('password')
    # 参数是否为空

    if username is None or username.strip() == '':
        context = {'userNameMessage': '账号不能为空！'}
        return render(request, "login.html", context)
    if password is None or password.strip() == '':
        context = {'passwordMessage': '密码不能为空！', 'username': username}
        return render(request, "login.html", context)
    # 用户名和密码进行匹配（如果数据库中是加密的，那么匹配数据库时，需要对密码进行加密）
    try:
        user = UserInfo.objects.get(userName=username, password=password)
        # 要记住登录状态
        request.session['userName'] = user.userName
        request.session.set_expiry(3600)  # 过多少秒过期
        # request.session.set_expiry(timedelta(seconds=10))
        # request.session.set_expiry(0)

        # return render(request, 'login_success.html', {'userName':username})
        # 重定向到首页，方便刷新，统一管理
        return render(request, 'login_success.html', {'userName':username})
    except UserInfo.DoesNotExist as e:
        """登录失败，没有匹配上"""
        context = {'message': '账号或密码错误！', 'username': username, 'password': password}
        return render(request, "login.html", context)

def logout(request):
    """如果没有编写方法的装饰器，那么能接受所有的类型的请求"""
    """退出，就用户的登录状态删除--删除session中的登录用户名"""
    # del request.session['userName'] # 第一种方式，删除session中的某个值
    request.session.flush()
    # request.session.clear() # 第三种方式：清空所有的session
    # return render(request, "login.html")
    # 重定向到index
    return HttpResponseRedirect(reverse('user:index'))

class UserView(View):
    def get(self,request,*args,**kwargs):
        params = request.GET
        print('接收Get传入的参数：',params)
        return HttpResponse('处理一个get方法')

    def post(self, request, *args, **kwargs):
        """处理post请求"""
        print('接收Post传入的参数：', request.POST)
        return HttpResponse("处理post请求方法。")

    def put(self, request, *args, **kwargs):
        """处理put请求方法"""
        params = request.body.decode(encoding='utf-8')
        print('接收Put传入的参数：', params)
        return HttpResponse("处理put请求方法。")

    def delete(self, request, *args, **kwargs):
        """处理put请求方法"""
        params = request.body.decode(encoding='utf-8')
        print('接收Delete传入的参数：', params)
        return HttpResponse("处理delete请求方法。")

    @require_GET
    def find(self, request, *args, **kwargs):
        """找不到此方法"""
        return HttpResponse("接收find方法。。。")

    def http_method_not_allowed(self, request, *args, **kwargs):
        print("不允许的方法。。。")
        return HttpResponse("不支持此方法: %s" % request.method, status=405)

"""模板视图"""
from django.views.generic.base import TemplateView
class HomeView(TemplateView):
    # 指定模板名称
    template_name = "home.html"
    # 查询上下文的数据
    def get_context_data(self, **kwargs):
        return {'users': UserInfo.objects.all()}

"""重定基本向视图"""
from django.views.generic.base import RedirectView

class UserRedirectView(RedirectView):
    permanent = True # 为True，禁止重定向
    url = '/user/home/' # 重定向的url
    query_string = True # 允许跳转携带浏览器指定的参数

    # pattern_name = 'user:home' # 重定向采用反向查询

class UserListView(ListView):
    model = UserInfo #指定查询的模型
    template_name = 'user_list.html'
    paginate_by = 1

    context_object_name = 'users'

from django.views.generic.detail import DetailView
class UserDetailView(DetailView):
    model = UserInfo

    # queryset = UserInfo.objects
    context_object_name = 'user' #指定模板获取数据key名
    template_name = 'user_detail.html'

    pk_url_kwarg = 'abc' #修改主键的参数名

    # pk_url_kwarg = 'abc' # 修改主键的参数名

    slug_field = 'slugUrl' #修改查询slug属性

    slug_url_kwarg = 'slug_value' #获取客户端slug的参数名字

def template(request,pk):
    return TemplateResponse(request,template='login.html')

user/templates/home.html
{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#    <head>#}
{#        <meta charset="UTF-8">#}
{#        <title>欢迎页面</title>#}
{#    </head>#}
{#    <body>#}
{#        <h1>这是欢迎页面</h1>#}
{#        <h2>{{ view }}</h2>#}
{#        <ul>#}
{#            {% for uesr in users %}#}
{#                <li>{{user.userName}} -- {{ user.password }}</li>#}
{#            {% endfor %}#}
{#        </ul>#}
{#    </body>#}
{#</html>#}

<h1>这是欢迎页面！</h1>
<h2>{{ view }}</h2>
<ul>
    {% for user in users %}
        <li>{{user.userName}} -- {{ user.password }}</li>
    {% endfor %}

</ul>

user/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录</title>
</head>
<body>
    <div style="margin: 200px 450px; vertical-align: center;">
        <form action="{% url 'user:login' %}" method="post"  >
            <p>
                <label>用户名：</label>
                <input id="userName" name="userName" placeholder="请输入用户名" value="{{ username }}"
                onfocus="clearForm();"/>
                <span style="color: red" id='userNameMessage'>{{ userNameMessage }}</span>
            </p>
            <p>
                <label>密&nbsp;&nbsp;&nbsp;&nbsp;码：</label>
                <input id="password" name="password" type="password" placeholder="请输入密码"
                       value="{{ password }}" onfocus="clearForm();" />
                <span style="color: red" id='passwordMessage'>{{ passwordMessage }}</span>
            </p>
            <p style="color:red;" id='message'>{{ message }}</p>
            <p>
                <button type="submit">登录</button>
                <button type="button" onclick="resetForm()">重置</button>
            </p>
        </form>
    </div>
    <script>
        function resetForm(){
            document.getElementById('userName').value='';
            document.getElementById('password').value='';
        }

        function clearForm() {

             document.getElementById('userNameMessage').innerHTML='';
             document.getElementById('passwordMessage').innerHTML='';
             document.getElementById('message').innerHTML='';
        }

    </script>
</body>
</html>

user/templates/login_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录成功</title>
</head>
<body>
    <h1>欢迎[{{ userName }}]登录成功！</h1>
    <a href="{% url 'user:logout' %}">退出</a>
</body>
</html>

user/templates/user_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>用户详情页</title>
</head>
<body>
    用户主键： {{ user.id }}<br>
    用户名字： {{ user.userName }}<br>
    用户密码： {{ user.password }}<br>
</body>
</html>

user/templates/user_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>用户列表</title>
</head>
<body>
   <h1>用户列表</h1>
    {% for user in object_list %}
        <li>{{user.userName}} -- {{ user.password }}</li>
    {% endfor %}
    总记录数： {{ paginator.count }}<br>
    总页数： {{ paginator.num_pages }}<br>
    分页导航：
        {% for num in paginator.page_range %}
            <a href="?page={{ num }}">{{ num }}</a>
        {% endfor %}
    <br>
    当前页： {{ page_obj }}
</body>
</html>