post_app/urls.py
# -*- coding:utf-8 -*-
from django.urls import path
from . import views

app_name = 'post_app'

urlpatterns = [

    path('add/', views.add, name='add'),
    path('index/', views.index, name='index'),

]

project_view/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('tpl/', include('tpl.urls')),
    path('uploader/', include('uploader.urls')),
    path('csrf/', include('csrf.urls')),
    path('jsonp/', include('jsonp.urls')),
    path('user/',include('user.urls')),
    path('cookie/',include('cookie.urls')),
    path('pro_response/',include('pro_response.urls')),
    path('ajax/',include('ajax.urls')),
    path('post_app/',include('post_app.urls')),
    path('get_app/',include('get_app.urls')),
    # path('http/',include(m_http.urls)),
    path('employee/', include('employee.urls')),
    # path('blog/', include('blog.urls')),
    # path('', include('articles.urls')),
    path('rs/', include('rs.urls')),
    path('admin/', admin.site.urls),
]

rs/urls.py
# -*- coding:utf-8 -*-
from django.urls import path
from . import views

app_name = 'rs'
urlpatterns = [
    path(route="test_rs/<int:pk>/", view=views.test_rs, name='test_rs'),
    path(route="test01/", view=views.test01, name='test01'),
]

post_app/models.py
from django.db import models

# Create your models here.

post_app/views.py
from django.shortcuts import render

# Create your views here.


def index(request):
    return render(request, 'post_index.html')


def add(request):
    """接收post请求数据"""
    params = request.POST
    print('获取参数：', params)
    uname = params.get('uname')
    upwd = params.get('upwd')
    gender = params.get('gender')
    interest = params.getlist('interest')
    print('姓名：%s\r\n密码：%s\r\n性别：%s\r\n爱好：%s' % (uname, upwd, gender, ','.join(interest)))
    # return render(request, 'add_success.html', context=params)
    context = {'uname': uname, 'upwd': upwd, 'gender': gender,
               'interest': interest}
    return render(request, 'add_success.html', context=context)

post_app/templates/add_success.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Title</title>
    </head>
    <body>
        <h1>添加成功</h1>
        <h2>显示用户数据</h2>
        <p><label>用户名：</label><span>{{ uname }}</span></p>
        <p><label>密码：</label><span>{{ upwd }}</span></p>
        <p><label>性别：</label><span>{{ gender }}</span></p>
        <p><label>兴趣：</label><span>{{ interest }}</span></p>
    </body>
</html>

post_app/templates/post_index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Post请求首页</title>
    </head>
    <body>
        <form method="post" action="{% url 'post_app:add' %}">
            {% csrf_token %}
            姓名：<input type="text" name="uname"/><br>
            密码：<input type="password" name="upwd"/><br>
            性别：
                <input type="radio" name="gender" value="1" checked />男
                 <input type="radio" name="gender" value="0"/>女<br>
            爱好：
                 <input type="checkbox" name="interest" value="听歌"/>听歌
                 <input type="checkbox" name="interest" value="旅游"/>旅游
                 <input type="checkbox" name="interest" value="看书"/>看书
                 <input type="checkbox" name="interest" value="睡觉"/>睡觉
            <br>
                <input type="submit" value="提交"/>
        </form>
    </body>
</html>