csrf/urls.py
from django.urls import path
from . import views

app_name = 'csrf'
urlpatterns = [
    path('form/', views.form, name='form'),
    path('home_ajax/', views.home_ajax, name='home_ajax'),

    path('home/', views.home, name='home'),
    path('index/', views.index, name='index'),

]

jsonp/urls.py
from django.urls import path
from . import views


urlpatterns = [

    path('callback/', views.callback, name='index'),
    path('index/', views.index, name='index'),

]

rs/urls.py
# -*- coding:utf-8 -*-
from django.urls import path
from . import views

app_name = 'rs'
urlpatterns = [
    path(route="test_rs/<int:pk>/", view=views.test_rs, name='test_rs'),
    path(route="test01/", view=views.test01, name='test01'),
]

tpl/urls.py
from django.urls import path
from . import views

app_name = 'tpl'

urlpatterns = [

    path('filter/', views.filter, name='filter'),
    path('<int:year>/path/<int:month>/<int:day>/', views.path, name='path'),
    path('user_list/', views.user_list, name='user_list'),
    path('show_user/<int:pk>/', views.show_user, name='show_user'),
    path('find/', views.find, name='find'),
    path('index/', views.index, name='index'),

]

uploader/urls.py
from django.urls import path
from . import views
from django.views.generic.base import RedirectView


app_name = 'uploader'
urlpatterns = [
    path('upload/', views.upload, name='upload'),
    path('index/', views.index, name='index'),

]

csrf/models.py
from django.db import models

# Create your models here.

jsonp/models.py
from django.db import models

# Create your models here.

uploader/models.py
from django.db import models

# Create your models here.

csrf/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
# Create your views here.

def index(request):
    return render(request,'csrf.html')

def home(request):
    return render(request,'csrf_home.html')

def home_ajax(request):
    return render(request,'csrf_home_ajax.html')

@csrf_exempt
def form(request):
    print(request.POST)
    return HttpResponse('接收参数')

jsonp/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.


def index(request):
    return render(request, 'jsonp.html')

import json
def callback(request):
    callback_name = request.GET.get('callback')

    result = {'username': '梦克', 'age': 18}
    result_str = json.dumps(result)
    if callback_name is not None:
        result_str = "%s(%s)" % (callback_name, result_str)
        return HttpResponse(result_str)
    else:
        return HttpResponse(result_str,
                            content_type='application/json;charset=utf-8')

uploader/views.py
from django.shortcuts import render
from django.views.decorators.http import require_POST
from django.http import HttpResponse


# Create your views here.


def index(request):
    """上传页面"""
    return render(request, 'uploader.html')


from qiniu import Auth, put_file, etag
import qiniu.config

def qiniu(key, localfile):
    access_key = 'BuyR7f5C1bovc8-IxXWjC145OFuXuX5-AEwO19fD'
    secret_key = 'keF4PpPSVondC7UFBP8oX0aZx9d3V9jRhJJXcIu7'
    # 构建鉴权对象
    q = Auth(access_key, secret_key)

    bucket_name = 'shsxt' # 七牛服务器需要创建一个空间

    # 生成上传 Token，可以指定过期时间等
    token = q.upload_token(bucket_name, key, 3600)

    # 要上传文件的本地路径
    ret, info = put_file(token, key, localfile)
    print(ret)
    print(info)

import datetime
from user.models import UserInfo
@require_POST
def upload(request):
    """处理上传文件，写入磁盘"""
    file = request.FILES.get('myfile') # 返回UploadedFile对象
    params = request.POST # 获取表单除了文件的其他表单域
    print(params)
    if file is None:
        return HttpResponse("请选择上传文件!")
    else:
        # 写入文件
        now = datetime.datetime.now().timestamp()
        # 确保文件名唯一
        filepath = 'C:/temp/%s-%s' % (now, file.name)
        with open(filepath, 'wb+') as f:
            for chunk in file.chunks():
                f.write(chunk)

        # 上传到七牛服务器
        filename = "%s-%s" % (now, file.name)
        qiniu(filename, filepath)

        # 写入数据库 name, age , header

        UserInfo.objects.create(userName=params.get('name'),
                                age=params.get('age'), header=filename)
        return render(request, 'uploader.html')

templates/common.html
<div style="background-color: aqua;">
    <ul style="list-style: none; display: -webkit-inline-box ">
        <li>{{ menu }} | </li>
        <li>下载 | </li>
        <li>文档 | </li>
        <li>捐赠</li>
    </ul>
</div>

templates/csrf.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>CSRF跨站请求伪造</title>
</head>
<body>
    <h1>模拟一下跨站请求:</h1>
    <form action="http://testphp.vulnweb.com/guestbook.php" method="post">
        <input name="name" value="test" type="hidden" />
        <textarea style="width: 271px; height: 68px" name="text"></textarea><br>
        <button type="submit" >提交</button>
    </form>
</body>
</html>

templates/csrf_home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>CSRF跨站请求伪造</title>
</head>
<body>
    <h1>模拟一下跨站请求:</h1>
    <form action="{% url 'csrf:form' %}" method="post">
        {% csrf_token %}
        <p><label>用户名：</label><input name="name" placeholder="输入用户名" /></p>
        <div><lable>自我介绍：</lable><textarea style="width: 271px; height: 68px" name="introduce"></textarea></div>
        <button type="submit" >提交</button>
    </form>
</body>
</html>

templates/csrf_home_ajax.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>CSRF跨站请求伪造</title>
</head>
<body>
    <h1>模拟一下跨站请求:</h1>
        {% csrf_token %}
        <input type="hidden" id="csrftoken" value="{{ csrf_token }}">
        <p><label>用户名：</label><input name="name" placeholder="输入用户名" /></p>
        <div><lable>自我介绍：</lable><textarea style="width: 271px; height: 68px" name="introduce"></textarea></div>
        <button type="button" onclick="add()" >提交</button>

</body>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script>
        function add() {
            $.post('../form/', {csrfmiddlewaretoken:$("#csrftoken").val()}, function (resp) {
                console.log(resp)
            })
        }
    </script>
</html>

templates/jsonp.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>JSONP访问数据</title>
</head>
<body>
    <h1>欢迎来到Jsonp的学习</h1>

{#    <script>#}
{#        function abc(resp) {#}
{#            console.log(resp)#}
{#        }#}
{#    </script>#}
{#    <script src="http://127.0.0.1:8000/jsonp/callback?callback=abc"></script>#}
{#    #}
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

    <script>
        $(document).ready(function() {
            {#$.getJSON('http://127.0.0.1:8000/jsonp/callback?callback=?', {}, function(resp) {#}
            {#    alert(resp)#}
            {#});#}
            $.ajax({
                'url': 'http://127.0.0.1:8000/jsonp/callback?callback=?',
                'type': 'get',
                'dataType': 'jsonp', // 返回jsonp进行处理
                'success': function(resp) {
                    alert(resp)
                }
            })
        });
    </script>


</body>
</html>

templates/list_dept.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>列表展示</title>
</head>
<body>
    <h1>部门信息列表</h1>
    <table border="1" cellspacing="0" cellpadding="0">
        <tr>
            <th>部门编号</th>
            <th>部门名称</th>
            <th>部门地址</th>
        </tr>
        {% for obj in objs %}
                <tr>
                    <td>{{ obj.deptNo }}</td>
                    <td>{{ obj.dname }}</td>
                    <td>{{ obj.loc }}</td>
                </tr>
        {% endfor %}

    </table>
</body>
</html>

templates/list_emp.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>列表展示</title>
</head>
<body>
    <h1>员工信息列表</h1>
    <table border="1" cellspacing="0" cellpadding="0">
        <tr>
            <th>员工编号</th>
            <th>员工姓名</th>
            <th>员工薪水</th>
            <th>员工部门</th>
            <th>上级领导</th>
            <th>入职日期</th>
        </tr>
        {% for obj in objs %}
                <tr>
                    <td>{{ obj.empNo }}</td>
                    <td>{{ obj.ename }}</td>
                    <td>{{ obj.sal }}</td>
                    <td>{{ obj.dept.dname }}</td>
                    <td>{{ obj.mgr.ename }}</td>
                    <td>{{ obj.hireDate }}</td>
                </tr>
        {% endfor %}
        <p>
            <label>输入工资等级ID：</label><input type="text" id="id" placeholder="请输入工资等级ID" />
            <button type="button" onclick="get();" >获取</button>
        </p>
        <p>显示工资等级：<span id="show"></span></p>
{#        <tr>#}
{#            <td>1</td>#}
{#            <td>张三</td>#}
{#            <td>1000</td>#}
{#            <td>研发部</td>#}
{#            <td>张怡彪</td>#}
{#            <td>2009-10-01</td>#}
{#        </tr>#}
{#        <tr>#}
{#            <td>1</td>#}
{#            <td>张三</td>#}
{#            <td>1000</td>#}
{#            <td>研发部</td>#}
{#            <td>张怡彪</td>#}
{#            <td>2009-10-01</td>#}
{#        </tr>#}

    </table>

    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script>
        function get() {
            // 获取输入的等级主键id的值
            var id = $("#id").val();
            // 发起ajax请求
            var url = '/employee/salegrade/' + id + '/';
            alert(url);

            $.ajax({
                'url': url, // 请求url
                'type':'get', // 请求方式
                'dataType': 'json', // 接收响应的数据格式json/html/text等
                'success': function(resp){ // 处理请求成功的回调函数
                    alert(resp);
                    if (resp != null && resp.code != null && resp.code == 500){
                         $("#show").html("没有找到。。")
                    } else {
                        $("#show").html(resp.lowsal +"---"+ resp.higsal)
                    }

                },
                'error': function () { // 处理失败的回调函数
                    console.log('处理失败。。')
                },
                'complete': function() { // 处理结束的回调函数
                    console.log('请求结束。。')
                }
            })

        }
    </script>

</body>
</html>

templates/test_revers.html
<html>
    <head>
        <title>这是测试反向解析</title>
        <meta charset="UTF-8" >
    </head>

    <body>
        <a href="{% url 'rs:test_rs' 12 %} " >跳转链接</a>
    </body>

</html>

templates/tpl_date.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>测试反向解析</title>
</head>
<body>
    <h1>反向解析结果</h1>
    <a href="{% url 'tpl:path' '1999' '12' '20' %}">跳转</a>
</body>
</html>

templates/tpl_filter.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>测试过滤器</title>
</head>
<body>
    <h1>用户信息：</h1>
    <p><label>姓名：</label><span>{{ userName|upper }}</span></p> {# 这是大写 #}
    <p><label>性别：</label><span>{% if gender == 1 %}男{% else %}女{% endif %}</span></p>
    <p><label>身高：</label><span>{{ height}}-{{ height|floatformat }}-{{ height|floatformat:2 }}</span></p>{# 浮点数精确位数 #}
    <p><label>生日：</label><span>{{ birthday|date:'Y-m-d'}}</span></p> {# 日期格式化 #}
    <p><label>生日：</label><span>{{ birthday|date:'y-M-D'}}</span></p>{# 日期格式化 #}
    <p><label>生日：</label><span>{{ birthday|date:'Y-m-d h:i:s a'}}</span></p>{# 日期时间格式化 #}
    <p><label>标签：</label><span>{{ tags|join:' | ' }}</span></p>{# list格式化 #}
    {% if tags|length_is:0 %}{# list长度判断  length_is:0也就是：length=0#}
        <p><label>存款：</label><span>{{ cash|default:999999999 }}</span></p>
    {% else %}
        <p><label>穷：</label><span>{{ cash|default:0 }}</span></p>
    {% endif %}
</body>
</html>

templates/tpl_index.html
<html>
    <head>
        <title>模板首页</title>
        <meta charset="UTF-8" >
    </head>

    <body>
        {% include 'common.html'  %}
        <div>debug: {{ debug }}</div>
        <div>request: {{ request.method }}/{{ request.path }}/{{ request.session.userName }}/{{ request.COOKIES }}</div>
        <div>auth: {{ auth }}</div>
        <div>message: {% for message in messages %}
        {{ message }}
    {% endfor %}</div>
    </body>

</html>

templates/tpl_user.html
<html>
    <head>
        <title>模板首页</title>
        <meta charset="UTF-8" >
    </head>

    <body>
        {% include 'common.html' %}
        <div>展示: {{ user.show }}</div>
        <div>年龄: {{ user.age }}</div>
        <div>用户名: {{ user.userName }}</div>
        <div>密码: {{ user.password }}</div>

    </body>

</html>

templates/tpl_user_list.html
<html>
    <head>
        <title>模板首页</title>
        <meta charset="UTF-8" >
    </head>

    <body>
        {% include 'common.html' %}
        <h1>用户列表展示:</h1>
        <table cellspacing="0" cellpadding="0" border="1">
            <tr>
                <th>序号</th>
                <th>用户ID</th>
                <th>用户名字</th>
                <th>密码</th>
                <th>Slug</th>
                <th>头像</th>
                <th>年龄</th>
            </tr>
            {% for user in users reversed  %} {# reversed代表反向遍历 #}
                {# 如果是第一行，那么标记红色，如果是最后一行标记绿色 #}
                {% comment %}
                    如果是第一行，
                    那么标记红色，
                    如果是最后一行标记绿色
                {% endcomment %}
                {% if forloop.first %}
                    <tr style="background-color: red">
                {% elif forloop.last %}
                    <tr style="background-color: green">
                {% elif forloop.counter|divisibleby:2 %}
                    <tr style="background-color: gray">
                {% else %}
                    <tr >
                {% endif %}
                    <td>{{ forloop.counter }}</td>
                    <td>{{ user.id }}</td>
                    <td>{{ user.userName }}</td>
                    <td>{{ user.password }}</td>
                    <td>{{ user.slugUrl|upper|lower }}</td>
                    <td>
                        {% if user.header is not None and user.header != '' %}
                            <a href="http://ojaxu1scr.bkt.clouddn.com/{{ user.header }}">
                                <img src="http://ojaxu1scr.bkt.clouddn.com/{{ user.header }}" width="45" height="45">
                            </a>
                        {% else %}
                            <a href="https://www.fengdu100.com/uploads/allimg/180624/1J5135917-0.jpg">
                                <img src="https://www.fengdu100.com/uploads/allimg/180624/1J5135917-0.jpg" width="45" height="45">
                            </a>
                        {% endif %}

                    </td>
                    <td>{{ user.age }}</td>
                </tr>
            {% endfor %}

        </table>

    </body>

</html>

templates/uploader.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>上传</title>
</head>
<body>
    <h1>文件上传</h1>
    <form action="{% url 'uploader:upload' %}" enctype="multipart/form-data" method="post" >
        {% csrf_token %}
        <div>姓名：<input name="name" placeholder="请输入姓名" /></div>
        <div style="margin-top: 10px;">年龄：<input name="age" placeholder="请输入姓名" /></div>
        <div style="margin-top: 10px;">头像：<input type="file" name="myfile" /></div>
        <button type="submit" style="margin-top: 10px;">注册</button>
    </form>
</body>
</html>