get_app/urls.py
# -*- coding:utf-8 -*-
from django.urls import path
from . import views

app_name = 'get_app'

urlpatterns = [

    path('handler_multi/', views.handler_multi, name='handler_multi'),
    path('handler_one/', views.handler_one, name='handler_one'),
    path('index/', views.index, name='index'),
    path('print_request/', views.print_request, name='print_request'),
]

project_view/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('tpl/', include('tpl.urls')),
    path('uploader/', include('uploader.urls')),
    path('csrf/', include('csrf.urls')),
    path('jsonp/', include('jsonp.urls')),
    path('user/',include('user.urls')),
    path('cookie/',include('cookie.urls')),
    path('pro_response/',include('pro_response.urls')),
    path('ajax/',include('ajax.urls')),
    path('post_app/',include('post_app.urls')),
    path('get_app/',include('get_app.urls')),
    # path('http/',include(m_http.urls)),
    path('employee/', include('employee.urls')),
    # path('blog/', include('blog.urls')),
    # path('', include('articles.urls')),
    path('rs/', include('rs.urls')),
    path('admin/', admin.site.urls),
]

rs/urls.py
# -*- coding:utf-8 -*-
from django.urls import path
from . import views

app_name = 'rs'
urlpatterns = [
    path(route="test_rs/<int:pk>/", view=views.test_rs, name='test_rs'),
    path(route="test01/", view=views.test01, name='test01'),
]

get_app/models.py
from django.db import models

# Create your models here.

get_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.decorators.http import require_GET

# Create your views here.


def print_request(request):
    """打印request对象的属性"""
    print(request.POST) # 获取POST请求的参数，其实就是请求体中的数据
    print(request.GET) # 获取Get请求的参数，其实就是QueryString数据
    print(request.method) # 打印请求方法
    print(request.META) # request元信息，是个字典
    print(request.path) # 获取请求路径(url)，包含请求host和port以及请求的query string
    print(request.body) # 获取请求体中的数据，字节
    print(request.get_full_path()) # 获取请求路径：去除host和port
    print(request.get_full_path_info()) # 获取请求路径信息
    print(request.is_ajax()) # 是否是XMLHTTPRequest请求(即ajax请求)， bool

    return HttpResponse('打印HttpRequest对象')


def index(request):
    return render(request, "index.html")


# 接收一键一值
@require_GET
def handler_one(request):
    # 接收参数
    a = request.GET.get('a') # 获取一个值
    b = request.GET.get('b')
    return render(request, "handler_one.html", context={'a':a, 'b':b})


@require_GET
def handler_multi(request):
    # 接收参数
    a = request.GET.getlist('a', 0)
    b = request.GET.get('b', 1)
    return render(request, "handler_multi.html", context={'a': a, 'b': b})

get_app/templates/handler_multi.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>
</head>
<body>
    <div>
        <p>a: {% for foo in a %}
            {% if forloop.last %} {# 是否是最后一个，不需要添加， #}
                {{ foo }}
            {% else %}
                {{ foo }},
            {% endif %}
        {% endfor %}
        </p>
        <p>b: {{ b }}</p>
    </div>
</body>
</html>

get_app/templates/handler_one.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>
</head>
<body>
    <div>
        <p>a: {{ a }}</p>
        <p>b: {{ b }}</p>
    </div>
</body>
</html>

get_app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>
</head>
<body>
    <div>
        <p><a href="{% url 'get_app:handler_one' %}?a=hello&b=world">一键一值</a></p>
        <p><a href="{% url 'get_app:handler_multi' %}?a=hello&a=hello2&b=world&b=world2">一键多值</a></p>
    </div>
</body>
</html>